language: php

php:
  - 5.4
  - 5.5
  - hhvm

notifications:
  email: false
  slack:
    secure: XqN13BBIJRNR65fhMiCdV+1/Va89xiE7OcsV9gGUi3ErEJUbppbF1MX237tfrIIxWAAhf5scRl2kllrkbnHjmXAqBzhqLxUXpsbB5EE6VHlKptamIKSFyaPh1NTPx45T/FI15i9eVmUoOpGneb0jjZqKHCIBRQd/otjttYvBer0=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
